package co.com.microservices.oferta.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.springframework.validation.annotation.Validated;
import javax.validation.Valid;
import javax.validation.constraints.*;

/**
 * Oferta
 */
@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-14T10:21:40.463-05:00")

@DynamoDBTable(tableName = "Oferta")
public class Oferta {
	@JsonProperty("idOferta")
	private String idOferta = null;

	@JsonProperty("producto")
	private String producto = null;

	@JsonProperty("detalle")
	private String detalle = null;

	@JsonProperty("foto")
	private String foto = null;

	@JsonProperty("idNegocio")
	private String idNegocio = null;

	@JsonProperty("tipo_oferta")
	private String tipoOferta = null;

	@JsonProperty("fecha_inicio")
	private String fechaInicio = null;

	@JsonProperty("fecha_fin")
	private String fechaFin = null;

	@JsonProperty("valor")
	private BigDecimal valor = null;

	@JsonProperty("nombreFoto")
	private String nombreFoto = null;

	public Oferta idOferta(String idOferta) {
		this.idOferta = idOferta;
		return this;
	}

	/**
	 * Get idOferta
	 * 
	 * @return idOferta
	 **/
	@ApiModelProperty(required = true, value = "")
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	public String getIdOferta() {
		return idOferta;
	}

	public void setIdOferta(String idOferta) {
		this.idOferta = idOferta;
	}

	public Oferta producto(String producto) {
		this.producto = producto;
		return this;
	}

	/**
	 * Get producto
	 * 
	 * @return producto
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull
	@DynamoDBAttribute

	public String getProducto() {
		return producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	public Oferta detalle(String detalle) {
		this.detalle = detalle;
		return this;
	}

	/**
	 * Get detalle
	 * 
	 * @return detalle
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull
	@DynamoDBAttribute

	public String getDetalle() {
		return detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	public Oferta foto(String foto) {
		this.foto = foto;
		return this;
	}

	/**
	 * Get foto
	 * 
	 * @return foto
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull
	@DynamoDBAttribute

	public String getFoto() {
		return foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	public Oferta idNegocio(String idNegocio) {
		this.idNegocio = idNegocio;
		return this;
	}

	/**
	 * Get idNegocio
	 * 
	 * @return idNegocio
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull
	@DynamoDBAttribute

	public String getIdNegocio() {
		return idNegocio;
	}

	public void setIdNegocio(String idNegocio) {
		this.idNegocio = idNegocio;
	}

	public Oferta tipoOferta(String tipoOferta) {
		this.tipoOferta = tipoOferta;
		return this;
	}

	/**
	 * Get tipoOferta
	 * 
	 * @return tipoOferta
	 **/
	@ApiModelProperty(value = "")
	@DynamoDBAttribute

	public String getTipoOferta() {
		return tipoOferta;
	}

	public void setTipoOferta(String tipoOferta) {
		this.tipoOferta = tipoOferta;
	}

	public Oferta fechaInicio(String fechaInicio) {
		this.fechaInicio = fechaInicio;
		return this;
	}

	/**
	 * Get fechaInicio
	 * 
	 * @return fechaInicio
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull
	@DynamoDBAttribute

	public String getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(String fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Oferta fechaFin(String fechaFin) {
		this.fechaFin = fechaFin;
		return this;
	}

	/**
	 * Get fechaFin
	 * 
	 * @return fechaFin
	 **/
	@ApiModelProperty(value = "")
	@NotNull
	@DynamoDBAttribute

	public String getFechaFin() {
		return fechaFin;
	}

	public void setFechaFin(String fechaFin) {
		this.fechaFin = fechaFin;
	}

	public Oferta valor(BigDecimal valor) {
		this.valor = valor;
		return this;
	}

	/**
	 * Get valor
	 * 
	 * @return valor
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull
	@DynamoDBAttribute
	@Valid

	public BigDecimal getValor() {
		return valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public Oferta nombreFoto(String nombreFoto) {
		this.nombreFoto = nombreFoto;
		return this;
	}

	/**
	 * Get nombreFoto
	 * 
	 * @return nombreFoto
	 **/
	@ApiModelProperty(required = true, value = "")
	@NotNull
	@DynamoDBAttribute

	public String getNombreFoto() {
		return nombreFoto;
	}

	public void setNombreFoto(String nombreFoto) {
		this.nombreFoto = nombreFoto;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Oferta oferta = (Oferta) o;
		return Objects.equals(this.idOferta, oferta.idOferta) && Objects.equals(this.producto, oferta.producto)
				&& Objects.equals(this.detalle, oferta.detalle) && Objects.equals(this.foto, oferta.foto)
				&& Objects.equals(this.idNegocio, oferta.idNegocio)
				&& Objects.equals(this.tipoOferta, oferta.tipoOferta)
				&& Objects.equals(this.fechaInicio, oferta.fechaInicio)
				&& Objects.equals(this.fechaFin, oferta.fechaFin) && Objects.equals(this.valor, oferta.valor)
				&& Objects.equals(this.nombreFoto, oferta.nombreFoto);
	}

	@Override
	public int hashCode() {
		return Objects.hash(idOferta, producto, detalle, foto, idNegocio, tipoOferta, fechaInicio, fechaFin, valor,
				nombreFoto);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Oferta {\n");

		sb.append("    idOferta: ").append(toIndentedString(idOferta)).append("\n");
		sb.append("    producto: ").append(toIndentedString(producto)).append("\n");
		sb.append("    detalle: ").append(toIndentedString(detalle)).append("\n");
		sb.append("    foto: ").append(toIndentedString(foto)).append("\n");
		sb.append("    idNegocio: ").append(toIndentedString(idNegocio)).append("\n");
		sb.append("    tipoOferta: ").append(toIndentedString(tipoOferta)).append("\n");
		sb.append("    fechaInicio: ").append(toIndentedString(fechaInicio)).append("\n");
		sb.append("    fechaFin: ").append(toIndentedString(fechaFin)).append("\n");
		sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
		sb.append("    nombreFoto: ").append(toIndentedString(nombreFoto)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
